services:
  mysql:
    image: mysql:8.0
    container_name: mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-network

#  # Spring Boot Backend
#  backend:
#    build:
#      context: ./backend
#      dockerfile: Dockerfile
#    container_name: backend-dev
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/locationdb
#      - SPRING_DATASOURCE_USERNAME=devuser
#      - SPRING_DATASOURCE_PASSWORD=devpassword
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mysql
#    networks:
#      - app-network
#
#  # Frontend (React/Vue/Angular)
#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    container_name: frontend-dev
#    environment:
#      - REACT_APP_API_URL=http://localhost:8080
#    ports:
#      - "3000:3000"
#    depends_on:
#      - backend
#    networks:
#      - app-network
#
#  # phpMyAdmin für DB-Management
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    container_name: phpmyadmin
#    environment:
#      PMA_HOST: mysql
#      PMA_PORT: 3306
#      PMA_USER: devuser
#      PMA_PASSWORD: devpassword
#    ports:
#      - "8081:80"
#    depends_on:
#      - mysql
#    networks:
#      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge